export const STRINGS = {
  appName: 'וורדל עברי',
  play: 'שחק',
  leaderboard: 'טבלת ניקוד',
  challenges: 'אתגרים',
  tournament: 'טורניר',
  profile: 'פרופיל',
  settings: 'הגדרות',
  todaysWord: 'המילה של היום',
  guessWord: 'נחש את המילה',
  youWon: 'כל הכבוד!',
  youLost: 'כמעט!',
  theSolutionWas: 'המילה הייתה',
  shareResult: 'שתף תוצאה',
  playAgain: 'שחק שוב',
  notAWord: 'לא מילה תקנית',
  tooShort: 'המילה קצרה מדי',
  watchAdForHint: 'צפה בפרסומת לרמז',
  hintRevealed: 'האות שנחשפה',
  signIn: 'כניסה עם גוגל',
  signOut: 'יציאה',
  daily: 'יומי',
  weekly: 'שבועי',
  allTime: 'כל הזמנים',
  rank: 'דירוג',
  guesses: 'ניחושים',
  time: 'זמן',
  streak: 'רצף',
  gamesPlayed: 'משחקים',
  winRate: 'אחוז ניצחון',
  createChallenge: 'צור אתגר',
  joinChallenge: 'הצטרף לאתגר',
  challengeCode: 'קוד אתגר',
  joinTournament: 'הצטרף לטורניר',
};
